# -*- coding: utf-8 -*-
"""LibraryManagementSystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Y3zSFE-IWpsWgK6cTzACtY8tW4MwWOI
"""

class Library:
    def __init__(self):
        self.file=open("books.txt","a+")

    def close_file(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        books=self.file.read().splitlines()
        if not books:
            print("No books found")
        else:
            for book in books:
                title,author,*rest=book.split(',')
                print(f"Title:{title},Author:{author}")

    def add_book(self):
        title=input("Enter book title:").strip()
        if not title:
            print("Please type a title")
            return
        author=input("Enter author:").strip()
        if not author:
            print("Please type an author")
            return
        year=input("Enter first release year:").strip()
        if not year:
            print("Please type a year")
            return
        pages=input("Enter number of pages:").strip()
        if not pages:
            print("Please enter a number")
            return
        book_info=f"{title},{author},{year},{pages}\n"
        self.file.write(book_info)
        print("Book added")

    def remove_book(self):
       title=input("Enter the title of the book to remove:").strip()
       if not title:
           print("Please type the title to remove")
           return
       self.file.seek(0)
       books= self.file.readlines()
       updated_books=[book for book in books if not book.lower().startswith(title.lower())]
       if len(updated_books)==len(books):
           print(f"Book'{title}'not found")
       else:
           self.file.seek(0)
           self.file.truncate()
           self.file.writelines(updated_books)
           print(f"Book'{title}'removed")

lib=Library()


while True:
    print("***MENU***")
    print("1)List Books")
    print("2)Add Books")
    print("3)Remove Books")
    print("q)Quit")

    choice=input("Enter your choice(1,2,3 or q):").strip().lower()
    if choice =='q':
        break
    if choice not in ['1','2','3']:
        print("Please type one of them:1,2,3 or q")
        continue
    if choice=='1':
        lib.list_books()
    elif choice=='2':
        lib.add_book()
    elif choice=='3':
        lib.remove_book()

lib.close_file()